language: node_js

node_js:
  - 10
  - 8

addons:
  apt:
    packages:
      - rethinkdb
    sources:
      - sourceline: 'deb https://download.rethinkdb.com/apt trusty main'
        key_url: 'https://download.rethinkdb.com/apt/pubkey.gpg'
